-- H2 兼容的建表脚本（用于单元/集成测试）
-- H2 MODE=MySQL，去掉 ENGINE/CHARSET/COMMENT 等 MySQL 特有语法

CREATE TABLE IF NOT EXISTS "user" (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(128) NOT NULL,
  nickname VARCHAR(64),
  phone VARCHAR(20),
  email VARCHAR(128),
  avatar VARCHAR(256),
  status TINYINT NOT NULL DEFAULT 1,
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_username ON "user"(username);

CREATE TABLE IF NOT EXISTS category (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  parent_id BIGINT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  category_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  subtitle VARCHAR(256),
  main_image VARCHAR(256),
  detail CLOB,
  price DECIMAL(12,2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart_item (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  checked TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_product ON cart_item(user_id, product_id);

CREATE TABLE IF NOT EXISTS order_main (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_no VARCHAR(32) NOT NULL,
  order_type VARCHAR(20) NOT NULL DEFAULT 'normal',
  seckill_session_id BIGINT,
  user_id BIGINT NOT NULL,
  total_amount DECIMAL(12,2) NOT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  receiver_name VARCHAR(64),
  receiver_phone VARCHAR(20),
  receiver_address VARCHAR(256),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_order_no ON order_main(order_no);

CREATE TABLE IF NOT EXISTS order_item (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  product_name VARCHAR(128) NOT NULL,
  product_image VARCHAR(256),
  price DECIMAL(12,2) NOT NULL,
  quantity INT NOT NULL,
  total_amount DECIMAL(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS review (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  rating TINYINT NOT NULL,
  content VARCHAR(512),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS after_sale (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  after_sale_no VARCHAR(32) NOT NULL,
  user_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  order_item_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  product_name VARCHAR(128) NOT NULL,
  product_image VARCHAR(256),
  type TINYINT NOT NULL,
  reason VARCHAR(128) NOT NULL,
  description VARCHAR(512),
  voucher_images VARCHAR(1024),
  original_price DECIMAL(12,2) NOT NULL,
  original_quantity INT NOT NULL,
  original_total_amount DECIMAL(12,2) NOT NULL,
  refund_amount DECIMAL(12,2),
  status TINYINT NOT NULL DEFAULT 0,
  reject_reason VARCHAR(256),
  return_company VARCHAR(64),
  return_tracking_no VARCHAR(64),
  exchange_company VARCHAR(64),
  exchange_tracking_no VARCHAR(64),
  supplement_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_after_sale_no ON after_sale(after_sale_no);

CREATE TABLE IF NOT EXISTS after_sale_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  after_sale_id BIGINT NOT NULL,
  operator_id BIGINT,
  operator_name VARCHAR(64),
  operator_role VARCHAR(20),
  action VARCHAR(64) NOT NULL,
  status_from TINYINT,
  status_to TINYINT,
  remark VARCHAR(512),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS after_sale_supplement (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  supplement_no VARCHAR(32) NOT NULL,
  after_sale_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  price_diff DECIMAL(12,2) NOT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  paid_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_supplement_no ON after_sale_supplement(supplement_no);

ALTER TABLE "user" ADD COLUMN IF NOT EXISTS points INT NOT NULL DEFAULT 0;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS total_consume DECIMAL(12,2) NOT NULL DEFAULT 0.00;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "level" TINYINT NOT NULL DEFAULT 1;

ALTER TABLE order_main ADD COLUMN IF NOT EXISTS points_discount DECIMAL(12,2) NOT NULL DEFAULT 0.00;
ALTER TABLE order_main ADD COLUMN IF NOT EXISTS points_used INT NOT NULL DEFAULT 0;
ALTER TABLE order_main ADD COLUMN IF NOT EXISTS points_earned INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS points_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  type TINYINT NOT NULL,
  change_points INT NOT NULL,
  balance INT NOT NULL,
  related_type VARCHAR(32),
  related_id BIGINT,
  remark VARCHAR(256),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_points_log_user ON points_log(user_id);

CREATE TABLE IF NOT EXISTS points_product (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  image VARCHAR(256),
  description VARCHAR(512),
  points_required INT NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS points_exchange_order (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  exchange_no VARCHAR(32) NOT NULL,
  user_id BIGINT NOT NULL,
  points_product_id BIGINT NOT NULL,
  product_name VARCHAR(128) NOT NULL,
  product_image VARCHAR(256),
  points_cost INT NOT NULL,
  receiver_name VARCHAR(64),
  receiver_phone VARCHAR(20),
  receiver_address VARCHAR(256),
  status TINYINT NOT NULL DEFAULT 0,
  express_company VARCHAR(64),
  express_no VARCHAR(64),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_exchange_no ON points_exchange_order(exchange_no);

CREATE TABLE IF NOT EXISTS seckill_session (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  product_id BIGINT NOT NULL,
  seckill_price DECIMAL(12,2) NOT NULL,
  total_stock INT NOT NULL,
  sold_stock INT NOT NULL DEFAULT 0,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  per_user_limit INT NOT NULL DEFAULT 1,
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS seckill_token (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(64) NOT NULL,
  session_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  expire_at TIMESTAMP NOT NULL,
  used TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_seckill_token ON seckill_token(token);

CREATE TABLE IF NOT EXISTS favorite_group (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name VARCHAR(64) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS favorite (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  group_id BIGINT,
  favor_price DECIMAL(12,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_fav_user_product ON favorite(user_id, product_id);

CREATE TABLE IF NOT EXISTS price_alert (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  target_price DECIMAL(12,2) NOT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  triggered_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_alert_user_prod_status ON price_alert(user_id, product_id, status);

